---
- name: Send notify to Telegram
  community.general.telegram:
    token: '6482398803:AAGxJOsriVhWRvsM-VMd4ZehsvfS0ZCUXQE'
    api_args:
      migrate_to_chat_id: -4018769422
      parse_mode: "markdown"
      text: "[{{ services }}] Source IP Address {{ source_addresses }} has been blocked - Reason: {{ reason }}"
      disable_web_page_preview: True
      disable_notification: True
